name: project_roster
description: A new Flutter project for Managing rosters here at BKMC Swabi.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  states_rebuilder: ^6.3.0
  colornames:
  uuid: ^3.0.7
  path_provider: ^2.1.1
  flex_color_scheme: ^7.3.1
  hive_flutter:
  freezed_annotation:
  json_annotation:
dev_dependencies:
  build_runner: ^2.4.6
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
